services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    ports:
      - "8070:8070"
    networks:
      - no-internet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

networks:
  no-internet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
